"""Integrate grade 4 first semester English textbook page into the site.

Purpose:
- Add the generated textbook page to site-manifest.json.
- Refresh homepage, README, SITE_MAINTENANCE, and SITE_FRAMEWORK references.
- Keep updates idempotent for the 2026-08-20 site update.

This is an intermediate task artifact, not a site runtime file.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, text: str) -> None:
    (ROOT / path).write_text(text, encoding="utf-8", newline="\n")


def update_manifest() -> None:
    path = ROOT / "site-manifest.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    data["updated"] = "2026-08-20"
    pages = data["pages"]
    if not any(page.get("id") == "english-grade-4-first-texts" for page in pages):
        entry = {
            "id": "english-grade-4-first-texts",
            "type": "english-textbook",
            "subject": "english",
            "title": "广州英语四年级上册课文朗读",
            "route": "/subjects/english/grade-4/first/texts/",
            "output": "subjects/english/grade-4/first/texts/index.html",
            "source": "content/english/texts/grade-4-first.json",
            "managed": "tools/build_textbook_page.py",
            "order": 400,
            "card": {
                "eyebrow": "四年级上学期 · 课文",
                "title": "广州英语四年级上册课文朗读",
                "summary": "Unit 1-8 · 176 句/项 · 逐句朗读",
            },
        }
        insert_at = next(
            (index for index, page in enumerate(pages) if page.get("id") == "english-grade-4-first-words"),
            len(pages),
        )
        pages.insert(insert_at, entry)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def update_home() -> None:
    path = "index.html"
    text = read(path)
    text = text.replace(
        "已收录三年级下学期、五年级下学期课文与单词，四年级、六年级上学期单词，以及四大常用时态专题",
        "已收录三年级下学期、四年级上学期、五年级下学期和六年级上学期英语内容，以及语法专题",
    )
    write(path, text)


def update_readme() -> None:
    path = "README.md"
    text = read(path)
    marker = "- `/subjects/english/grade-4/first/words/`：英语四年级上学期单词词汇。"
    item = "- `/subjects/english/grade-4/first/texts/`：英语四年级上学期课文。"
    if item not in text and marker in text:
        text = text.replace(marker, item + "\n" + marker, 1)
    write(path, text)


def update_maintenance() -> None:
    path = "SITE_MAINTENANCE.md"
    text = read(path)
    text = text.replace("最后更新：2026-07-28", "最后更新：2026-08-20")
    dir_marker = "- `subjects/english/grade-4/first/words/index.html`：英语四年级上学期单词词汇页。"
    dir_item = "- `subjects/english/grade-4/first/texts/index.html`：英语四年级上学期课文页。"
    if dir_item not in text and dir_marker in text:
        text = text.replace(dir_marker, dir_item + "\n" + dir_marker, 1)
    page_marker = "- `/subjects/english/grade-4/first/words/`"
    page_item = "- `/subjects/english/grade-4/first/texts/`"
    if page_item not in text and page_marker in text:
        text = text.replace(page_marker, page_item + "\n" + page_marker, 1)
    changelog = (
        "### 2026-08-20\n\n"
        "- 使用 `english-textbook-html` skill 和课文页生成框架新增广州英语四年级上册课文朗读页："
        "Unit 1-8，共 176 个朗读/译文块；源文本只有英文，已补充中文译文，并接入英语二级清单页。\n\n"
    )
    if "### 2026-08-20" not in text:
        text = text.replace("## 变更记录\n\n", "## 变更记录\n\n" + changelog, 1)
    write(path, text)


def update_framework() -> None:
    path = "SITE_FRAMEWORK.md"
    text = read(path)
    if "      texts/\n        grade-4-first.json\n        grade-6-first.json\n" not in text:
        text = text.replace(
            "      texts/\n        grade-6-first.json\n",
            "      texts/\n        grade-4-first.json\n        grade-6-first.json\n",
            1,
        )
    text_item = "四年级上学期课文：content/english/texts/grade-4-first.json"
    if text_item not in text:
        text = text.replace(
            "六年级上学期课文：content/english/texts/grade-6-first.json",
            text_item + "\n六年级上学期课文：content/english/texts/grade-6-first.json",
            1,
        )
    comment_item = "<!-- Generated from content/english/texts/grade-4-first.json by tools/build_textbook_page.py. Do not edit this file directly. -->"
    if comment_item not in text:
        text = text.replace(
            "<!-- Generated from content/english/texts/grade-6-first.json by tools/build_textbook_page.py. Do not edit this file directly. -->",
            comment_item
            + "\n<!-- Generated from content/english/texts/grade-6-first.json by tools/build_textbook_page.py. Do not edit this file directly. -->",
            1,
        )
    write(path, text)


def main() -> None:
    update_manifest()
    update_home()
    update_readme()
    update_maintenance()
    update_framework()
    print("UPDATED grade 4 first texts integration")


if __name__ == "__main__":
    main()
