from __future__ import annotations

import argparse
import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VOCAB_DIR = ROOT / "content" / "english" / "vocab"


def esc(value: str) -> str:
    return html.escape(str(value), quote=True)


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def item_count(data: dict) -> int:
    return sum(len(unit.get("items", [])) for unit in data.get("units", []))


def read_button(text: str) -> str:
    label = esc(text)
    return (
        f'<button class="read-btn" type="button" title="朗读" '
        f'aria-label="朗读：{label}" data-text="{label}">'
        '<svg viewBox="0 0 20 20" aria-hidden="true">'
        '<path d="M5 3.5v13l11-6.5-11-6.5z"></path>'
        "</svg></button>"
    )


def render_row(item: dict) -> str:
    english = esc(item["english"])
    chinese = esc(item["chinese"])
    phonetic = esc(item["phonetic"])
    return f"""              <tr>
                <td>
                  <div class="vocab-word">
                    <span>{english}</span>
                    {read_button(item["english"])}
                  </div>
                </td>
                <td>{chinese}</td>
                <td class="phonetic">{phonetic}</td>
              </tr>"""


def render_unit(unit: dict, count_suffix: str) -> str:
    rows = "\n".join(render_row(item) for item in unit.get("items", []))
    count = len(unit.get("items", []))
    return f"""      <article class="reader-unit vocab-unit" id="{esc(unit['id'])}">
        <header class="reader-unit-header">
          <p>{esc(unit['label'])} · {count} {esc(count_suffix)}</p>
          <h2>{esc(unit['title'])}</h2>
        </header>
        <div class="vocab-table-wrap">
          <table class="vocab-table">
            <thead>
              <tr><th>English</th><th>中文</th><th>音标</th></tr>
            </thead>
            <tbody>
{rows}
            </tbody>
          </table>
        </div>
      </article>"""


def render_page(data: dict, source_path: Path) -> str:
    stats = data.get("stats", {})
    unit_label = stats.get("unit_label", f"{len(data.get('units', []))} 个 Unit")
    item_suffix = stats.get("item_suffix", "条")
    total_items = item_count(data)
    nav = "\n".join(
        f'        <a href="#{esc(unit["id"])}">{esc(unit["label"])}</a>'
        for unit in data.get("units", [])
    )
    unit_suffix = data.get("unit_item_suffix", item_suffix)
    units = "\n".join(render_unit(unit, unit_suffix) for unit in data.get("units", []))
    rel_source = source_path.relative_to(ROOT).as_posix()

    return f"""<!doctype html>
<!-- Generated from {rel_source} by tools/build_vocab_page.py. Do not edit this file directly. -->
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{esc(data['description'])}">
  <title>{esc(data['page_title'])}</title>
  <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="/assets/css/site.css">
  <script src="/assets/js/site-shell.js" defer></script>
</head>
<body data-nav="english">
  <div data-site-header></div>
  <main class="reader-shell vocab-shell">
    <section class="reader-hero" aria-labelledby="reader-title">
      <div>
        <p class="kicker">{esc(data['kicker'])}</p>
        <h1 id="reader-title">{esc(data['title'])}</h1>
        <p>{esc(data['summary'])}</p>
      </div>
      <div class="reader-stats" aria-label="词汇统计">
        <span>{esc(unit_label)}</span>
        <span>{total_items} {esc(item_suffix)}</span>
      </div>
    </section>

    <div data-reader-tools></div>
    <nav class="reader-unit-nav" aria-label="单元导航">
{nav}
    </nav>

    <section class="dictation-panel" data-dictation aria-label="听写模式">
      <div class="dictation-toolbar">
        <button class="dictation-toggle" type="button" data-dictation-toggle aria-expanded="false" aria-pressed="false" aria-controls="dictationTray">听写</button>
      </div>
      <div class="dictation-tray" id="dictationTray" data-dictation-tray hidden tabindex="-1" aria-label="听写词汇"></div>
    </section>

    <section class="vocab-units" aria-label="词汇内容">
{units}
    </section>
  </main>
  <div data-site-footer></div>
  <button class="back-top" type="button" id="topButton" aria-label="返回顶部">顶部</button>
  <script src="/assets/js/textbook-reader.js" defer></script>
</body>
</html>
"""


def build_file(source_path: Path) -> Path:
    data = read_json(source_path)
    if data.get("schema") != "english-vocab-page.v1":
        raise ValueError(f"Unsupported schema in {source_path}")
    target = ROOT / data["output"]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_page(data, source_path), encoding="utf-8", newline="\n")
    return target


def main() -> None:
    parser = argparse.ArgumentParser(description="Build English vocabulary HTML pages from content JSON.")
    parser.add_argument("--all", action="store_true", help="Build every JSON file in content/english/vocab.")
    parser.add_argument("sources", nargs="*", help="Specific vocabulary JSON files to build.")
    args = parser.parse_args()

    if args.all:
      sources = sorted(VOCAB_DIR.glob("*.json"))
    else:
      sources = [ROOT / source for source in args.sources]
    if not sources:
        parser.error("Pass --all or one or more source JSON files.")

    for source in sources:
        target = build_file(source)
        print(f"BUILT {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
